# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a92e669e5c08bef117a0fe6c06954b5af9dcc4503799c8dc00f8e80b544f6c21de3a5f2daa3e5e294e13a259b635976d387119e987857c7c22b8d39efbbf2c60

test:
  secret_key_base: 7e5893c0e4f94154475cf712f8f42ba224ce5158622870e92e76e47bec58cc676fe910faf5851398b08aa7ee9e7c2c7aadeaa30447a33a40dfd91c319cabcc07

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
